import type { Metadata } from "next";
import Sidebar from "@/app/_components/Sidebar";
import "./globals.css";
import "material-symbols";

export const metadata: Metadata = {
  title: "Cloit Assignment",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <div className="flex">
            <Sidebar />
            <div className="w-10/12 h-screen p-5">
                {children}
            </div>
        </div>
      </body>
    </html>
  );
}
