import type { Metadata } from "next";
import Sidebar from "@/app/_components/Sidebar";
import "./globals.css";
import "material-symbols";
import StoreProvider from '@/app/StoreProvicer';

export const metadata: Metadata = {
  title: "Cloit Assignment",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <StoreProvider>
          <div className="flex">
              <Sidebar />
              <div className="md:w-10/12 min-w-80 h-screen p-5">
                  {children}
              </div>
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}
